### ISSUE TITLE
REST API:  "Content-Type" header is "text/plain"

### ISSUE THREAD

**Issue by Ctere1** [Abbas-gheydi/radotp#1]
In the [web package](https://github.com/Abbas-gheydi/radotp/blob/main/pkgs/web/api.go), the `makeJsonResponse` function returns `Content-Type` header as `text/plain`.

Go's ResponseWriter requires that you set all headers before calling `WriteHeader`. Just moving the line that sets `Content-Type` above the `WriteHeader` line and all should be good.

So, changing this code: 

```GO
func makeJsonResponse(w http.ResponseWriter, juser JsonUSer, statusCode int) {
	w.WriteHeader(statusCode)
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(juser)
}
```
To: 

```GO
func makeJsonResponse(w http.ResponseWriter, juser JsonUSer, statusCode int) {
	w.Header().Set("Content-Type", "application/json")
        w.WriteHeader(statusCode)
	json.NewEncoder(w).Encode(juser)
}
```
solves this problem.

**Comment by Abbas-gheydi** [comment]
Thanks.
This issue is [fixed](https://github.com/Abbas-gheydi/radotp/commit/94bf1656fa2a4f2529bff971a01b1c4c94eac6bd).

**Comment by Ctere1** [comment]
Thank you.
