### ISSUE TITLE
FG Invalid secret for the server 

### ISSUE THREAD

**Issue by kadder** [abbas-gheydi/radotp#11]
Hello. 
I'm trying to connect FG to radotp, for SSLVPN 2FA implentation
But when I try to test connectivity, it gives an error
![image](https://github.com/user-attachments/assets/dc0e18c0-87b8-4357-8a98-ec6ea563f28d)
My FortiOS is 7.4.5
My config: 
Authentication_Mode = "two_fa"

Could you please help me with that

**Comment by abbas-gheydi** [comment]
Hi dear @kadder ,

If you change the secret in radiusd.conf, you should restart the radotp container to apply this change.

**Comment by kadder** [comment]
I have resolved issue. 
Downgrade to Forti OS v7.4.3 helped me. 
Due to errors in firmware FortiGate always shows error invalid secret for the server.
